In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r'anime.csv')

In [5]:
df.head(n=10)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5     6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6     7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7     8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8     9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9    10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03

In [6]:
df.loc[3]['Title']

'Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members'

## Function to extract episode from dataframe

In [19]:
def extract_ep(txt):
    check=False
    extracted=''
    for i in txt:
        if i==')':
            return extracted[1:]
        if i=='(':
            check=True
        if check==True:
            extracted+=i

In [20]:
df['episodes']=df['Title'].apply(extract_ep)
df['episodes']

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: episodes, dtype: str

In [27]:
df['episodes']=df['episodes'].str.replace(' eps','')

In [29]:
df['episodes']=df['episodes'].astype(int)

## Function to extract Month range of anime episodes/Air duration

In [37]:
def extract_air(txt):
    check=False
    data=""
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range(i+1,i+20):
                data+=txt[j]
            return data

In [40]:
df['air-duration']=df['Title'].apply(extract_air)
df.head()

,Rank,Title,Score,episodes,air_count,air-duration
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr 2019 - Jul 2019

In [42]:
# Split start and end dates
df[['start', 'end']] = df['air-duration'].str.split(' - ', expand=True)

# Convert to datetime
df['start'] = pd.to_datetime(df['start'], format='%b %Y')
df['end'] = pd.to_datetime(df['end'], format='%b %Y')

# Calculate duration in months (inclusive)
df['months'] = (
    (df['end'].dt.year - df['start'].dt.year) * 12
    + (df['end'].dt.month - df['start'].dt.month)
    + 1
)

df.head()

,Rank,Title,Score,episodes,air_count,air-duration,start,end,months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,Apr 2009 - Jul 2010,2009-04-01,2010-07-01,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,Apr 2011 - Sep 2011,2011-04-01,2011-09-01,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,Oct 2022 - Dec 2022,2022-10-01,2022-12-01,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,Apr 2015 - Mar 2016,2015-04-01,2016-03-01,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,Apr 2019 - Jul 2019,2019-04-01,2019-07-01,4